#!/usr/bin/perl -w
#
# Copyright (C) 2009 Michael Daum http://michaeldaumconsulting.com
#
# For licensing info read LICENSE file in the Foswiki root.
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details, published at 
# http://www.gnu.org/copyleft/gpl.html

# Set library paths in @INC, at compile time
BEGIN {
  if (-e './setlib.cfg') {
    unshift @INC, '.';
  } elsif (-e '../bin/setlib.cfg') {
    unshift @INC, '../bin';
  }
  require 'setlib.cfg';
}

use strict;

use Foswiki ();
use Foswiki::Plugins::SolrPlugin;
my $foswiki = new Foswiki();
my $indexer = Foswiki::Plugins::SolrPlugin::getIndexer($foswiki);

my $query = $ARGV[0]||'';
if ($query) {
  $indexer->deleteByQuery($query);
  #$indexer->optimize();
}
$indexer->commit(1);

Foswiki::Plugins::SolrPlugin::finishPlugin();

1;
