#!/bin/sh
### BEGIN INIT INFO
# Provides:          solrworker
# Required-Start:    $remote_fs $syslog mattdaemon
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start solrworker.
### END INIT INFO
set -eu
##############################################################################
export FOSWIKI_ROOT="/var/www/qwikis/qwiki"
BIN="./mattworker"
PIDFILE="/var/run/solrworker.pid"
PARAMS="--department=\"SolrPlugin\" -d $PIDFILE"
WORKER_USER=www-data
LOGFILE=$FOSWIKI_ROOT/working/logs/solrindex.log

. /lib/lsb/init-functions

##############################################################################

case "${1:-}" in
    start)
        if [ -f "$PIDFILE" ] ; then
            log_warning_msg "Warning: solrworker already running, doing nothing (PIDFILE $PIDFILE exists)"
            exit 1
        fi

        log_daemon_msg "Starting solrworker" "solrworker"
        set +e
        cd $FOSWIKI_ROOT
        cd tools

        # start daemon
        touch $PIDFILE
        chown $WORKER_USER $PIDFILE
        su -c "cd $FOSWIKI_ROOT/tools; FOSWIKI_ROOT=$FOSWIKI_ROOT $BIN $PARAMS" $WORKER_USER 2>> $LOGFILE
        RC=$?
        set -e
        log_end_msg $RC
        ;;

    stop)
        if [ -f "$PIDFILE" ] ; then
            log_daemon_msg "Stopping solrworker" "solrworker"
            set +e
            /sbin/start-stop-daemon -K -p $PIDFILE
            RC=$?
            rm -f $PIDFILE
            set -e
            log_end_msg $RC
        else
            log_success_msg "No solrworker running"
        fi
        ;;

    status)
        if [ -f "$PIDFILE" ]
        then
            PROCESS="$(cat $PIDFILE)"
            if ps -p $PROCESS > /dev/null
            then
                log_success_msg "solrworker with pid $PROCESS is running"
                exit 0
            else
                log_warning_msg "solrworker with pid $PROCESS is NOT running"
                exit 1
            fi
        else
            log_warning_msg "Could not find a running solrworker (no PID file)"
            exit 1
        fi
        ;;

    restart|reload|force-reload)
        $0 stop
        $0 start
        ;;

    *)
        echo "Usage: ${0:-} {start|stop|restart|reload|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0
